### ISSUE TITLE
Where to get the app?

### ISSUE THREAD

**Issue by IzzySoft** [Yash-K-B/YMPlayer#3]
Just wondering if the APK is available somewhere for those interested? Maybe you could [tag your releases](https://github.com/Yash-K-B/YMPlayer/releases) and attach it there? Thanks in advance!

**Comment by Yash-K-B** [comment]
Right now not available anywhere. I will add soon.

**Comment by IzzySoft** [comment]
Wonderful, thanks! Please give me a ping when it's there :star_struck:

**Comment by Yash-K-B** [comment]
Application is available in the release section.

**Comment by IzzySoft** [comment]
Thanks! But wow, that's quite big. Do you plan for per-ABI APKs? That would bring e.g. the arm64 APK down to ~25 MB (about 1/3 the size of the current APK).
